lib/trello_clone_client_web/router.ex
defmodule TrelloCloneClientWeb.Router do
  use TrelloCloneClientWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TrelloCloneClientWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authenticated do
    plug TrelloCloneClientWeb.Plugs.AuthenticatedPipeline
    plug TrelloCloneClientWeb.Plugs.CurrentUser
  end

  pipeline :unauthenticated do
    plug TrelloCloneClientWeb.Plugs.UnauthenticatedPipeline
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TrelloCloneClientWeb do
    pipe_through [:browser, :unauthenticated]

    get "/signin", SessionController, :new
    post "/signin", SessionController, :signin
    get "/create", SessionController, :create
    get "/register", RegistrationController, :index
    post "/register", RegistrationController, :register
  end

  scope "/", TrelloCloneClientWeb do
    pipe_through [:browser, :authenticated]

    get "/logout", SessionController, :logout

    get "/", HomeController, :index
    get "/home", HomeController, :index

    resources "/boards", BoardController

  end

  # Other scopes may use custom stacks.
  # scope "/api", TrelloCloneClientWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TrelloCloneClientWeb.Telemetry
    end
  end
end

lib/trello_clone_client_web/views/nav_view.ex
defmodule TrelloCloneClientWeb.NavView do
  use TrelloCloneClientWeb, :view

end

lib/trello_clone_client_web/templates/nav/navbar.html.eex
<nav class="nav-bar">
  <div class="nav-container">
    <div class="justify-between w-auto static block justify-start" >
      <a class="nav-title"
        href="/"
        > &#128214; TRELLO CLONE</a >
    </div>
    <div class="flex flex-grow items-center lg:shadow-none"  >
      <ul class="flex flex-row list-none ml-auto">
        <%= case @access_token do %>
          <% nil -> %>
            <%= link to: Routes.session_path(TrelloCloneClientWeb.Endpoint, :new) do %>
              <li class="flex items-center">
                <button
                  class="nav-btn"
                  type="button"> Sign in </button>
              </li>
            <% end %>
            <%= link to: Routes.registration_path(TrelloCloneClientWeb.Endpoint, :index) do %>
              <li class="flex items-center">
                <button
                  class="nav-btn"
                  type="button"> Register </button>
            </li>
            <% end %>
          <% _access_token -> %>
            <li class="flex items-center text-gray-200">Hi <%= @current_user.email %>!</li>
            <%= link to: Routes.session_path(TrelloCloneClientWeb.Endpoint, :logout) do%>
              <li class="flex items-center">
                <button
                  class="nav-btn"
                  type="button"> Logout </button>
              </li>
            <% end %>
        <% end %> 
      </ul>
    </div>
  </div>
</nav>

lib/trello_clone_client_web/templates/nav/sidebar.html.leex
<div class="sidebar">
  <div class="flex my-2">
    <%= link to: Routes.home_path(TrelloCloneClientWeb.Endpoint, :index) do%>
      <svg class="h-10 w-10 font-bold <%= if @active == "home", do: "text-gray-100", else: "text-gray-500" %>"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <polyline points="5 12 3 12 12 3 21 12 19 12" />  
        <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" />  
        <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" />
      </svg>
    <% end %>
  </div>
  <div class="flex">
    <%= link to: Routes.board_path(TrelloCloneClientWeb.Endpoint, :index) do%>
      <svg class="h-10 w-10 font-bold <%= if @active == "board", do: "text-gray-100", else: "text-gray-500" %>"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" 
        stroke-linejoin="round" 
        stroke-width="2" 
        d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01"/>  
      </svg>
    <% end %>
  </div>
</div>